### ISSUE TITLE
Hey forgery810, question with your VIxx code 

### ISSUE THREAD

**Issue by ToomuchToosoon** [forgery810/fl-studio-alesis-vixx#1]
Firstly, can't say thanks enough for the coding work. 
Quick question, I am using the VI25 controller, and am looking to load your software. When I load it into the fruity loops directory, I can't get it to show up as an option under my midi settings in my DAW. 

Any suggestions?

Thanks

**Comment by forgery810** [comment]
Thanks. I hope it is helpful.
I should be getting around to updating it soon.

Do you have the file in its own folder within /settings/hardware ?
As in:
 Documents\Image-Line\FL Studio\Settings\Hardware\alesis_ai\
device_AlesisVIxx.py

It won't work if it is in the Hardware folder on its own.
It should appear on the top right on the list of midi controllers as
Alesis VIxx

That is the only issue I can think of. If it persists let me know and I
will try to recreate the problem.

Thanks again
Tyson

**Comment by forgery810** [comment]
Also let me know if you do get it working so I know if there is something
wrong.
Thanks

**Comment by axelbsa** [comment]
Had the same issue fixed by placing the *.py-file in a new directory under .../Hardware

I re-read the readme and it states "Place the .py file into a new folder (the name of which is your choice)" which i must have skipped. Because i just read ".py file into .... Documents/Image-Line/FL Studio/Settings/Hardware/"

But thanks for the work :)

**Comment by ToomuchToosoon** [comment]
Hey forgery810, took me a second to get back to this. I was transitioning from a HP to a Mac. 
Definitely works on the macbook pro, many thanks dude. I'll come back and post links to some tracks :)
