### ISSUE TITLE
Not an issue, just want to say THANK YOU SO MUCH!

### ISSUE THREAD

**Issue by HelgenX** [forgery810/fl-studio-alesis-vixx#2]
Your really saved me from using Ableton lol. I wanted to have all the functions so bad on my VI49. I want to donate to you, where can I do so? Also, I made a youtube video (giving you proper credit) about how to do this.

**Comment by forgery810** [comment]
Thanks. I'm glad to hear it is helping out. Funny you messaged me because I had just started working on updating it with more functionality right when you sent it. So hopefully I can figure out some useful stuff to add. If you find that there is a shortcut you want added let me know. 
No worries about donating. Thanks for the video, I'll add a link to it.

**Comment by HelgenX** [comment]
Thanks so much dude! I didn't want to just link it without a response, but I uploaded it here:

https://www.youtube.com/watch?v=eP1-_sq_YQI

As of now, I think it's damn perfect, I can't believe you went the lengths to turn the smaller buttons into something much more functional than intended! I almost feel like making a physical overlay for the keyboard with your functions, haha.

**Comment by forgery810** [comment]
I was hoping to remember all the buttons but I just ended up putting some tape down and writing out the functions. 
Also, to not have to push the buttons twice you can use the Alesis editor to change the switches to momentary rather than toggle.

**Comment by HelgenX** [comment]
> I was hoping to remember all the buttons but I just ended up putting some tape down and writing out the functions.
> Also, to not have to push the buttons twice you can use the Alesis editor to change the switches to momentary rather than toggle.

OH man, that saves me time! I will add that to the video description! Thanks!
