### ISSUE TITLE
File does not appear in ´´controller type´´ List

### ISSUE THREAD

**Issue by JimbosBeerbo** [forgery810/fl-studio-alesis-vixx#3]
Hey,

after I placed the ´device_AlesisVIxx.py´ File in Documents\Image-Line\FL Studio\Settings\Hardware\alesis_ai it doesn't appear in the ´´controller type´´ List. I have restarted everything related (PC, FL, MIDI) but Still nothing.

I hope you can help me and thanks for your Coding bruv!

**Comment by forgery810** [comment]
I'm not sure why it wouldn't show up. Try just cloning the whole folder, unzipping and copying to 
 Documents\Image-Line\FL Studio\Settings\Hardware\ 
The file needs to be within another folder and not just in ...\Hardware\ itself. It also can't be any deeper. So it should be
Documents\Image-Line\FL Studio\Settings\Hardware\fl-studio-alesis-vixx-main\device_AlesisVIxx.py

Also make sure that in the FL Program, under Options - File Settings, that User data folder is set to C:\Users\--your-username--\Documents\Image-Line

If not, reset it, and restart the program. If you are storing your data elsewhere you can set it back to the way it was and it should work.

It should appear on the top right of the controller list under Scripts and not mixed in with the others.
I'm also assuming you are using the latest version of FL studio.
Hopefully that helps.

**Comment by JimbosBeerbo** [comment]
Hey,

the file is in the right folder and the User data folder is also set correctly, but I haven't downloaded the latest version yet so maybe that is the problem. On which Versions have you tested the script.

thanks for the help

**Comment by forgery810** [comment]
It should work for any of the recent versions. Unless you are running FL 12 or something it should work. Also, try adding a script for a different midi controller and seeing if it shows up.

**Comment by JimbosBeerbo** [comment]
Hey, 

I updated my FL Studio finally and it worked. Thank you so much for your fast responses and coding. You really helped me.
