### ISSUE TITLE
Sustain Pedal plugged in the MIDI Keyboard activates same function as Key 17

### ISSUE THREAD

**Issue by simplebunsen** [forgery810/fl-studio-alesis-vixx#4]
Leaving this issue for a friend.

He has a sustain pedal plugged into his Midi Keyboard, which seemed to activate the same function "new pattern" as  Key 17.

This is what the debug log outputs when the sustain is being pressed.

`Alesis VIxx (user):  B0  40  7F  Control Change: Damper pedal (sustain)
Handled (first chance)  Absolute 0%
Alesis VIxx (user):  B0  40  00  Control Change: Damper pedal (sustain)
Handled (first chance)  Absolute 0%`

Commenting out these lines disables the unintended sustain pedal behaviour as well as the Key 17.

`elif event.data1 == switch["new_pattern"]:
print('Open New Pattern')
transport.globalTransport(midi.FPT_F4, 63)
event.handled = True`

Thanks for your hard work!

**Comment by forgery810** [comment]
Thank you for bringing this to my attention. I unfortunately never tested the sustain. I wanted to use the default Alesis config as much as possible but it does look like it uses CC 64 twice for some reason. 

I will upload a new configuration for the keyboard with the sustain CC set to 96 instead (and the switches set to momentary) so you should be able to use both the button and sustain without them conflicting. I actually should maybe add some functionality options for the sustain in the next version.

Thanks again!

**Comment by forgery810** [comment]
Also the config I uploaded probably only works for the vi61. If the keyboard is a 25 or 49 then you'll have to edit it with the aforementioned changes if you want to keep the new pattern functionality.
