### ISSUE TITLE
Alesis vi49 not working

### ISSUE THREAD

**Issue by Under-44** [forgery810/fl-studio-alesis-vixx#5]
![image](https://user-images.githubusercontent.com/69401550/146254905-cda7a6ac-0252-4d09-8898-cbe31db278f2.png)
![image](https://user-images.githubusercontent.com/69401550/146255057-4f1b13ab-54ac-48ef-b8c3-a9df972ec805.png)
![image](https://user-images.githubusercontent.com/69401550/146255114-283eb212-2ccc-47a5-b6ca-a6a78afb7c5f.png)

not sure how to fix it, cant figure it out.
(let me know if you need any more info).

**Comment by forgery810** [comment]
Is anything working at all, the play button for example?
Did you upload the .vi4 layout files to your keyboard?

If that isn't issue....

1. Update to the latest version of Fl Studio. 

2. If it still isn't working, start up FL, go to View / script output, hit a button, turn a knob, and then copy what shows up there, and post it here.

Thanks

**Comment by Under-44** [comment]
![image](https://user-images.githubusercontent.com/69401550/146262124-b131b800-383b-4c64-8ac7-89e390f68743.png)
i uploaded the keyboard files and updated the daw, didn't work

**Comment by forgery810** [comment]
I think you have it in the wrong folder. The downloaded folder should be placed in:
"Documents\Image-Line\FL Studio\Settings\Hardware\ "


If you do get it working, please let me know if you have any issues with the layout as I have not been able to test it on a the 49 key version.

**Comment by Under-44** [comment]
![image](https://user-images.githubusercontent.com/69401550/146272961-536249f3-3140-47ac-9d51-3196e5b29fca.png)
![image](https://user-images.githubusercontent.com/69401550/146272991-bd5416d3-f4db-43ef-a439-d1d2de5f9988.png)
![image](https://user-images.githubusercontent.com/69401550/146273059-5f636ce8-1386-41c4-ae16-acf162ed89d8.png)
![image](https://user-images.githubusercontent.com/69401550/146273348-783a15b7-65fe-4dda-a795-3e0dd9a3cf58.png)
i upload both right?

welp still no sign of anything. Sorry for the inconvenience.

**Comment by forgery810** [comment]
Yes, to different slots, but that isn't the issue.
I'm a little confused because your midi scripting version should be at 18 with the DAW update, but it is at 7 still.

The problem is with the python version FL Studio is using so I'll have to think about why your version is older still.

**Comment by Under-44** [comment]
i got it working, i'm using the 0.0.1 version, can't use the mod wheel feature since old version but its fine.

cheers boss great program.

**Comment by forgery810** [comment]
I made a new branch that got rid of the plugins module to see if that makes it usable on older versions.
You can try it here
https://github.com/forgery810/fl-studio-alesis-vixx/tree/1-02B
In my brief attempt at using it, it seemed to work ok.
The only functional difference is that you won't be able to use the controller for plugins.
Try that and let me know if it works.

I'm not sure what the issue could be with the earlier version, unfortunately.

**Comment by Under-44** [comment]
`// it works now, thanks so much for the help my dude.`

**Comment by Under-44** [comment]
![image](https://user-images.githubusercontent.com/69401550/146336614-24acfe19-83f6-4d64-b3d1-f1799f805a26.png)

found bug
kept on doing this like 100 times

alse found this when selecting pad per channel mode
![image](https://user-images.githubusercontent.com/69401550/146343355-5d08e9de-36ca-49f1-a5e0-24f24504ecfd.png)
![image](https://user-images.githubusercontent.com/69401550/146343522-5d3b1074-49ae-48dd-81f0-99f2e43cb19f.png)

only on these keys.

**Comment by forgery810** [comment]
Ok so this isn't going to work. Too much of the functionality depends on the DAW being updated.

Did you update to 20.9?

**Comment by Under-44** [comment]
no i didn't, it still works to a tier that's fine with me. atleast the buttons do things so i'm fine with it.

Thanks for the help.
