### ISSUE TITLE
FL 21.0.3 Won't Read File Correctly (Vi49)

### ISSUE THREAD

**Issue by GreenSpartanX54** [forgery810/fl-studio-alesis-vixx#6]
Recently my MIDI buttons have stopped working correctly in FL. Each time I change the Controller type it changes to "Akai FL Studio Fire" instead of the script. I've updated to the most recent version of the script and it still will not work. I have factory reset my MIDI and that didn't work either. I'm not sure what the problem is. all help is appreciated. Thank you.

**Comment by forgery810** [comment]
There is a new layout for this script. Have you uploaded it to the
controller with the Alesis program?
